version: 2
snapshot:
  widths: [1600]
  min-height: 1024
  percy-css: |
    #socialanimation-graphicWrapper #pendulum-graphicWrapper .grecaptcha-badge, .cookie-banner, .chat-widget { display: none !important; }